### ISSUE TITLE
Form field with errors

### ISSUE THREAD

**Issue by blackchestnut** [blackchestnut/blackchestnut.github.io#11]
Ruby
```ruby
# config/initializers/field_with_error.rb

ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
  "<div class='field_with_errors'>
    #{html_tag}
    <div class='error_message'>
      #{instance.error_message.first}
    </div>
  </div>".html_safe
end
```

CSS example
```css
.field_with_errors {
  display: inline-block;
}

.field_with_errors > input[type=text],
.field_with_errors > input[type=password],
.field_with_errors > textarea {
  background-color: #FFEBEE;
  border-bottom: #E53935 solid 1px;
}

.field_with_errors > .error_message {
  color: #D32F2F;
  display: inline-block;
}
```
