### ISSUE TITLE
Enum humanized keys

### ISSUE THREAD

**Issue by blackchestnut** [blackchestnut/blackchestnut.github.io#7]
```ruby
# app/models/game.rb
class Game < ApplicationRecord
  enum kind: { training: 0, friendly_match: 1 }
end
```

### Only in english
```slim
// app/views/games/new.html.slim
label Kind
= f.select :kind, Game.kinds.keys.map { |key| [key.humanize, key] })
```

### I18n
```yaml
ru:
  activerecord:
    attributes:
      game:
        kinds:
          training: Тренировка
          friendly_match: Товарищеский матч
```
```ruby
# app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.human_enum_name(name, value)
    I18n.t("activerecord.attributes.#{model_name.i18n_key}.#{name.to_s.pluralize}.#{value}")
  end
end
```
```slim
// app/views/games/new.html.slim
label Kind
= f.select :kind, Game.kinds.keys.map { |key| [Game.human_enum_name(:kind, key), key] }
```
